# Generated by Django 2.2.24 on 2021-08-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_sequences', '0016_through_model_for_user_partition_groups_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsequence',
            name='usage_key_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='learningsequence',
            unique_together={('learning_context', 'usage_key'), ('learning_context', 'usage_key_hash')},
        ),
    ]
