# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-13 22:25
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0003_courseteam_organization_protected'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeammateLove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='TeammateLoveMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(blank=True, db_index=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='teammatelove',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.TeammateLoveMessage'),
        ),
        migrations.AddField(
            model_name='teammatelove',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_loves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teammatelove',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_loves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teammatelove',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.CourseTeam'),
        ),
    ]
