# Generated by Django 2.2.19 on 2021-03-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0018_add_waffle_flag_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persistentgradesenabledflag',
            name='enabled_for_all_courses',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='CoursePersistentGradesFlag',
        ),
    ]
