# Generated by Django 2.2.19 on 2021-03-25 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0019_auto_20210325_2033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersistentGradesEnabledFlag',
        ),
    ]
